In [22]:
import pandas as pd
import seaborn as sns
import sklearn
import matplotlib.pyplot as plt
import numpy as np
import six
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score
%matplotlib inline

## Get the Data



In [6]:
df = pd.read_csv("spambase.data")
df.head()

word_freq_make  word_freq_address  word_freq_all  word_freq_3d  \
0            0.00               0.64           0.64           0.0   
1            0.21               0.28           0.50           0.0   
2            0.06               0.00           0.71           0.0   
3            0.00               0.00           0.00           0.0   
4            0.00               0.00           0.00           0.0   

   word_freq_our  word_freq_over  word_freq_remove  word_freq_internet  \
0           0.32            0.00              0.00                0.00   
1           0.14            0.28              0.21                0.07   
2           1.23            0.19              0.19                0.12   
3           0.63            0.00              0.31                0.63   
4           0.63            0.00              0.31                0.63   

   word_freq_order  word_freq_mail  ...  char_freq_;  char_freq_(  \
0             0.00            0.00  ...         0.00        0.000   
1             0.00            0.94  ...         0.00        0.132   
2             0.64            0.25  ...         0.01        0.143   
3             0.31            0.63  ...         0.00        0.137   
4             0.31            0.63  ...         0.00        0.135   

   char_freq_[  char_freq_!  char_freq_$  char_freq_#  \
0          0.0        0.778        0.000        0.000   
1          0.0        0.372        0.180        0.048   
2          0.0        0.276        0.184        0.010   
3          0.0        0.137        0.000        0.000   
4          0.0        0.135        0.000        0.000   

   capital_run_length_average  capital_run_length_longest  \
0                       3.756                          61   
1                       5.114                         101   
2                       9.821                         485   
3                       3.537                          40   
4                       3.537                          40   

   capital_run_length_total  Decision  
0                       278         1  
1                      1028         1  
2                      2259         1  
3                       191         1  
4                       191         1  

[5 rows x 58 columns]

In [7]:
df.shape

(4601, 58)

In [8]:
df = df.fillna(df.mean())

In [11]:
X = df.iloc[:,:54]
y = df['Decision']

In [12]:
from sklearn.model_selection import train_test_split

In [13]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [14]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [15]:
X_train.shape, X_test.shape

((3220, 54), (1381, 54))

##  DT



In [16]:
from sklearn.tree import DecisionTreeClassifier

In [17]:
dtree = DecisionTreeClassifier(max_depth = 7, criterion = 'gini')

In [18]:
dtree.fit(X_train,y_train)

DecisionTreeClassifier(max_depth=7)

## Predictions



In [19]:
predictions = dtree.predict(X_test)

In [28]:
print('Training set score: {:.2f}'.format(dtree.score(X_test,y_test)))

Training set score: 0.90


In [67]:
from sklearn.metrics import classification_report,confusion_matrix

In [68]:
print(classification_report(y_test,predictions))

              precision    recall  f1-score   support

           0       0.88      0.95      0.91       804
           1       0.92      0.82      0.87       577

    accuracy                           0.90      1381
   macro avg       0.90      0.88      0.89      1381
weighted avg       0.90      0.90      0.89      1381



In [69]:
print(confusion_matrix(y_test,predictions))

[[765  39]
 [105 472]]


## Random Forest

In [70]:
from sklearn.ensemble import RandomForestClassifier

In [71]:
#forest = RandomForestClassifier(criterion='gini', n_estimators=100) 
# n_estimators - число деревьев
forest = RandomForestClassifier()

In [72]:
forest.fit(X_train, y_train)

RandomForestClassifier()

In [73]:
predictions_rf= forest.predict(X_test)

In [74]:
from sklearn.metrics import classification_report,confusion_matrix

In [75]:
print(confusion_matrix(y_test,predictions_rf))

[[779  25]
 [ 49 528]]


In [76]:
print(classification_report(y_test,predictions_rf))

              precision    recall  f1-score   support

           0       0.94      0.97      0.95       804
           1       0.95      0.92      0.93       577

    accuracy                           0.95      1381
   macro avg       0.95      0.94      0.94      1381
weighted avg       0.95      0.95      0.95      1381



## Gridsearch RandFor

In [95]:
#param_grid = {'C': [0.1,1, 10, 100, 1000], 'gamma': [1,0.1,0.01,0.001,0.0001], 'kernel': ['rbf']} 

param_grid = {'criterion' : ['gini', 'entropy'], 'n_estimators':[1, 10, 100, 500], 'max_depth':[5,7,8,9,10], 'max_features':[3,4,5]}

In [96]:
from sklearn.model_selection import GridSearchCV

In [97]:
grid = GridSearchCV(RandomForestClassifier(),param_grid,refit=True,verbose=3)

In [98]:
grid.fit(X_train,y_train)

Fitting 5 folds for each of 120 candidates, totalling 600 fits
[CV] criterion=gini, max_depth=5, max_features=3, n_estimators=1 .....
[CV]  criterion=gini, max_depth=5, max_features=3, n_estimators=1, score=0.742, total=   0.0s
[CV] criterion=gini, max_depth=5, max_features=3, n_estimators=1 .....
[CV]  criterion=gini, max_depth=5, max_features=3, n_estimators=1, score=0.811, total=   0.0s
[CV] criterion=gini, max_depth=5, max_features=3, n_estimators=1 .....
[CV]  criterion=gini, max_depth=5, max_features=3, n_estimators=1, score=0.772, total=   0.0s
[CV] criterion=gini, max_depth=5, max_features=3, n_estimators=1 .....
[CV]  criterion=gini, max_depth=5, max_features=3, n_estimators=1, score=0.873, total=   0.0s
[CV] criterion=gini, max_depth=5, max_features=3, n_estimators=1 .....
[CV]  criterion=gini, max_depth=5, max_features=3, n_estimators=1, score=0.868, total=   0.0s
[CV] criterion=gini, max_depth=5, max_features=3, n_estimators=10 ....
[CV]  criterion=gini, max_depth=5, max_fe

[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   2 out of   2 | elapsed:    0.0s remaining:    0.0s


[CV]  criterion=gini, max_depth=5, max_features=3, n_estimators=10, score=0.891, total=   0.0s
[CV] criterion=gini, max_depth=5, max_features=3, n_estimators=10 ....
[CV]  criterion=gini, max_depth=5, max_features=3, n_estimators=10, score=0.890, total=   0.0s
[CV] criterion=gini, max_depth=5, max_features=3, n_estimators=100 ...
[CV]  criterion=gini, max_depth=5, max_features=3, n_estimators=100, score=0.894, total=   0.3s
[CV] criterion=gini, max_depth=5, max_features=3, n_estimators=100 ...
[CV]  criterion=gini, max_depth=5, max_features=3, n_estimators=100, score=0.907, total=   0.3s
[CV] criterion=gini, max_depth=5, max_features=3, n_estimators=100 ...
[CV]  criterion=gini, max_depth=5, max_features=3, n_estimators=100, score=0.894, total=   0.3s
[CV] criterion=gini, max_depth=5, max_features=3, n_estimators=100 ...
[CV]  criterion=gini, max_depth=5, max_features=3, n_estimators=100, score=0.904, total=   0.3s
[CV] criterion=gini, max_depth=5, max_features=3, n_estimators=100 ...


[Parallel(n_jobs=1)]: Done 600 out of 600 | elapsed:  5.4min finished


GridSearchCV(estimator=RandomForestClassifier(),
             param_grid={'criterion': ['gini', 'entropy'],
                         'max_depth': [5, 7, 8, 9, 10],
                         'max_features': [3, 4, 5],
                         'n_estimators': [1, 10, 100, 500]},
             verbose=3)

In [99]:
grid.best_params_

{'criterion': 'gini', 'max_depth': 10, 'max_features': 4, 'n_estimators': 100}

In [100]:
grid.best_estimator_

RandomForestClassifier(max_depth=10, max_features=4)

In [101]:
grid_predictions = grid.predict(X_test)

In [102]:
print(confusion_matrix(y_test,grid_predictions))

[[784  20]
 [ 77 500]]


In [103]:
print(classification_report(y_test,grid_predictions))

              precision    recall  f1-score   support

           0       0.91      0.98      0.94       804
           1       0.96      0.87      0.91       577

    accuracy                           0.93      1381
   macro avg       0.94      0.92      0.93      1381
weighted avg       0.93      0.93      0.93      1381

